# Generated by Django 5.0.3 on 2024-04-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
